service: faunadb-class-lambda

plugins:
    - serverless-deployment-bucket
    - serverless-plugin-include-dependencies

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: us-west-2
    deploymentBucket:
        name: faunadb-resource-bucket
        serverSideEncryption: AES256

functions:
    fauna:
        handler: fauna.handler
        # TODO
        # memorySize: 256

resources:
    Description: The SLS template for deploying the FaunaDB custom resource backing Lambda

# The following is a sample of how to use the custom resource in the same Serverles template

#    Resources:
#        # Our custom resource
#        FaunaDB:
#            Type: Custom::FaunaDB
#            Properties:
#                ServiceToken:
#                    Fn::GetAtt:
#                        - FaunaLambdaFunction
#                        - Arn

    Outputs:
        FaunaResourceArn:
            Value:
                Fn::GetAtt:
                    - FaunaLambdaFunction
                    - Arn
            Export:
                # This is the export name for the Custom Resource Lambda
                # Change this to what you want to reference from other stacks with Fn::ImportValue
                Name: fauna-class-lambda-arn